[project]
name = "lpm-py"
version = "0.1.0"
description = "A local package installer for python (to be used with locally hosted gitea)."
authors = [{ name = "Adam Worsnip" }]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["click (>=8.4.1,<9.0.0)", "platformdirs (>=4.10.0,<5.0.0)", "requests (>=2.34.2,<3.0.0)"]

[project.scripts]
lpm = "lpm.entrypoint:main"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
packages = [{ include = "lpm" }]
